# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Presenc' do
 
use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

#FB
pod 'Bolts'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'


end

target 'PresencTests' do

end

target 'PresencUITests' do

end

